/*
 * SQLite Service API
 * This is a REST API specification for SQLite Service.
 *
 * OpenAPI spec version: TRUNK-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.amdocs.aia.il.sqlite.client.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
