package com.amdocs.aia.il.common.publisher;

import java.util.Map;
import java.util.concurrent.atomic.AtomicLong;

public enum CounterType {
    //Audit
    REPLICATORLOAD,
    REPLICATORGEN,
    RECORDSLOADEDGEN,
    RECORDSMERGEDGEN,
    RECORDSSTOREDGEN,
    RECORDSDROPPEDGEN,
    TRANSFORMERAUDIT,
    BULKREPLICATOR,
    COMPUTLEADINGKEYLOAD,
    COMPUTLEADINGKEYMERGE,
    COMPUTLEADINGKEYSTORE,
    COMPUTLEADINGKEYDROPPED,
    COMPUTLEADINGKEY,
    TRANSIENTTRANSFORMERLOAD,
    TRANSIENTTRANSFORMERSTORE,


    //Kafka Collector Bulk/Ongoing
    KAFKACOLLECTOR,
    KAFKALOAD,
    KAFKASTORE,

    //Replicator Load Counters
    RECORDSLOADED,
    RECORDSMERGED,
    RECORDSSTORED,
    RECORDSDELETED,
    RECORDSNOCHANGE,
    RECORDSERROR,
    RECORDSDROPPED,

    REPLICATOR,
    TRANSFORMER,
    COMPUTELEADINGKEYS,
    BULKTRANSFORMER,
    REFERENCESTOREPUBLISHER,
    TRANSIENTTRANSFORMER,

    //Common for RTP
    PUBLISHCOUNT,
    UPSERTWRITECOMPLETED,
    UPSERTREADCOMPLETED,
    LEADINGKEYSQUERYCOUNT,
    RECORDSPROCESSED,
    LEADINGKEYSPERCONTEXTPERSOURCEDATACHANNEL,
    LEADINGKEYSPERCONTEXTPERSOURCEDATACHANNELCOMPUTED,
    //TRANSFORMER SPECIFIC
    TRANSFORMEDMESSAGECOUNTERPERTARGETENTITY,
    TRANSFORMEDMESSAGECOUNTERPERTARGETENTITYPUBLISHED,
    LEADINGKEYWITHMISSINGROOTCOUNTERPERCONTEXT,
    OUTPUTTRANSACTIONSCOUNTERPERSUBJECTAREA,
    TRANSFORMEDMESSAGECOUNTERINVALIDTARGETENTITYVALIDATION,
    TRANSACTIONMESSAGELENGTHFORKAFKA2,
    TRANSACTIONMESSAGESIZEFROMINTERMEDIATEKAFKA,

        //REPLICATOR SPECIFIC
    UPSERTCALLCOUNTPERDATACHANNELPERMB,
    PUBLISHCALLCOUNTPERDATACHANNELPERMB,
    INPUTMESSAGESCOUNTPERDATACHANNELPERMB,
    INPUTMESSAGESCOUNTPERTABLEDATACHANNELPERMB,
    UPSERTMAINDATACOUNTERPERTABLEPERMB,
    UPSERTRELATIONALDATACOUNTERPERTABLEPERMB,
    UPSERTFILTEREDMESSAGESCOUNTERPERTABLEPERMB,
    UPSERTFAILEDMESSAGESCOUNTERPERTABLEPERMB,
    DELETECOUNTERPERTABLEPERMB,
    MESSAGESENTTOINTERMEDIATEKAFKACOUNTERPERSUBAREAPERMB,
    TRANSACTIONMESSAGESIZETOINTERMEDIATEKAFKAPERMB,
    TRANSACTIONMESSAGESIZEFROMKAFKA1PERDATACHANNEL,

    PARTIALTRXMESSAGESCOUNTPERDATACHANNELPERMB,
    PARTIALTRXMESSAGESTOTALREADTIMEPERDATACHANNELPERMB,
    PARTIALTRXMESSAGESTOTALWRITETIMEPERDATACHANNELPERMB,
    NUMBEROFMICROBATCHESPERMB,
    NUMBEROFCONFLICTSPERMB,
    NUMBEROFINCOMPLETETRXPERMB
}
