/*
 * Integration Layer Configuration API
 * This is a REST API specification for Integration Layer Configuration application.
 *
 * OpenAPI spec version: TRUNK-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.amdocs.aia.il.configuration.client.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * EntityTransformationGridElementDTO
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "entityTransformationType", visible = true )
@JsonSubTypes({
  @JsonSubTypes.Type(value = CachedEntityTransformationGridElementDTO.class, name = "CACHED"),
  @JsonSubTypes.Type(value = SharedEntityTransformationGridElementDTO.class, name = "SHARED"),
})

public class EntityTransformationGridElementDTO {
  /**
   * Entity Transformation Type
   */
  public enum EntityTransformationTypeEnum {
    SHARED("SHARED"),
    
    CACHED("CACHED");

    private String value;

    EntityTransformationTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static EntityTransformationTypeEnum fromValue(String value) {
      for (EntityTransformationTypeEnum b : EntityTransformationTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("entityTransformationType")
  private EntityTransformationTypeEnum entityTransformationType = null;

  public EntityTransformationGridElementDTO entityTransformationType(EntityTransformationTypeEnum entityTransformationType) {
    this.entityTransformationType = entityTransformationType;
    return this;
  }

   /**
   * Entity Transformation Type
   * @return entityTransformationType
  **/
  @ApiModelProperty(required = true, value = "Entity Transformation Type")
  public EntityTransformationTypeEnum getEntityTransformationType() {
    return entityTransformationType;
  }

  public void setEntityTransformationType(EntityTransformationTypeEnum entityTransformationType) {
    this.entityTransformationType = entityTransformationType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EntityTransformationGridElementDTO entityTransformationGridElement = (EntityTransformationGridElementDTO) o;
    return Objects.equals(this.entityTransformationType, entityTransformationGridElement.entityTransformationType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(entityTransformationType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EntityTransformationGridElementDTO {\n");
    
    sb.append("    entityTransformationType: ").append(toIndentedString(entityTransformationType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

