/*
 * Integration Layer Configuration API
 * This is a REST API specification for Integration Layer Configuration application.
 *
 * OpenAPI spec version: TRUNK-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.amdocs.aia.il.configuration.client.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * additional information regarding the management of the external schema in the system&#39;s data channel which serves as the input for transformations
 */
@ApiModel(description = "additional information regarding the management of the external schema in the system's data channel which serves as the input for transformations")

public class ExternalSchemaDataChannelInfoDTO {
  @JsonProperty("dataChannelName")
  private String dataChannelName = null;

  /**
   * The format in which messages are serialized in the data channel
   */
  public enum SerializationMethodEnum {
    SHAREDPROTOBUF("SharedProtobuf"),
    
    SHAREDJSON("SharedJson");

    private String value;

    SerializationMethodEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static SerializationMethodEnum fromValue(String value) {
      for (SerializationMethodEnum b : SerializationMethodEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("serializationMethod")
  private SerializationMethodEnum serializationMethod = null;

  public ExternalSchemaDataChannelInfoDTO dataChannelName(String dataChannelName) {
    this.dataChannelName = dataChannelName;
    return this;
  }

   /**
   * The PHYSICAL name of the data channel
   * @return dataChannelName
  **/
  @ApiModelProperty(value = "The PHYSICAL name of the data channel")
  public String getDataChannelName() {
    return dataChannelName;
  }

  public void setDataChannelName(String dataChannelName) {
    this.dataChannelName = dataChannelName;
  }

  public ExternalSchemaDataChannelInfoDTO serializationMethod(SerializationMethodEnum serializationMethod) {
    this.serializationMethod = serializationMethod;
    return this;
  }

   /**
   * The format in which messages are serialized in the data channel
   * @return serializationMethod
  **/
  @ApiModelProperty(value = "The format in which messages are serialized in the data channel")
  public SerializationMethodEnum getSerializationMethod() {
    return serializationMethod;
  }

  public void setSerializationMethod(SerializationMethodEnum serializationMethod) {
    this.serializationMethod = serializationMethod;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExternalSchemaDataChannelInfoDTO externalSchemaDataChannelInfo = (ExternalSchemaDataChannelInfoDTO) o;
    return Objects.equals(this.dataChannelName, externalSchemaDataChannelInfo.dataChannelName) &&
        Objects.equals(this.serializationMethod, externalSchemaDataChannelInfo.serializationMethod);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dataChannelName, serializationMethod);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExternalSchemaDataChannelInfoDTO {\n");
    
    sb.append("    dataChannelName: ").append(toIndentedString(dataChannelName)).append("\n");
    sb.append("    serializationMethod: ").append(toIndentedString(serializationMethod)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

