/*
 * Integration Layer Configuration API
 * This is a REST API specification for Integration Layer Configuration application.
 *
 * OpenAPI spec version: TRUNK-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.amdocs.aia.il.configuration.client.dto;

import java.util.Objects;
import java.util.Arrays;
import com.amdocs.aia.il.configuration.client.dto.ExternalSchemaCollectionRulesDTO;
import com.amdocs.aia.il.configuration.client.dto.InvalidFilenameActionTypeDTO;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * ExternalCsvSchemaCollectionRulesDTO
 */

public class ExternalCsvSchemaCollectionRulesDTO extends ExternalSchemaCollectionRulesDTO {
  @JsonProperty("defaultInvalidFilenameAction")
  private InvalidFilenameActionTypeDTO defaultInvalidFilenameAction = null;

  public ExternalCsvSchemaCollectionRulesDTO defaultInvalidFilenameAction(InvalidFilenameActionTypeDTO defaultInvalidFilenameAction) {
    this.defaultInvalidFilenameAction = defaultInvalidFilenameAction;
    return this;
  }

   /**
   * Default file name mismatch behaviour
   * @return defaultInvalidFilenameAction
  **/
  @ApiModelProperty(value = "Default file name mismatch behaviour")
  public InvalidFilenameActionTypeDTO getDefaultInvalidFilenameAction() {
    return defaultInvalidFilenameAction;
  }

  public void setDefaultInvalidFilenameAction(InvalidFilenameActionTypeDTO defaultInvalidFilenameAction) {
    this.defaultInvalidFilenameAction = defaultInvalidFilenameAction;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExternalCsvSchemaCollectionRulesDTO externalCsvSchemaCollectionRules = (ExternalCsvSchemaCollectionRulesDTO) o;
    return Objects.equals(this.defaultInvalidFilenameAction, externalCsvSchemaCollectionRules.defaultInvalidFilenameAction) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(defaultInvalidFilenameAction, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExternalCsvSchemaCollectionRulesDTO {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    defaultInvalidFilenameAction: ").append(toIndentedString(defaultInvalidFilenameAction)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

