/*
 * Integration Layer Configuration API
 * This is a REST API specification for Integration Layer Configuration application.
 *
 * OpenAPI spec version: TRUNK-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.amdocs.aia.il.configuration.client.dto;

import java.util.Objects;
import java.util.Arrays;
import com.amdocs.aia.il.configuration.client.dto.BulkGroupDTO;
import com.amdocs.aia.il.configuration.client.dto.ExternalEntityDTO;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * SetFiltersRequestDTO
 */

public class SetFiltersRequestDTO {
  @JsonProperty("entities")
  private List<ExternalEntityDTO> entities = null;

  @JsonProperty("bulkGroup")
  private BulkGroupDTO bulkGroup = null;

  public SetFiltersRequestDTO entities(List<ExternalEntityDTO> entities) {
    this.entities = entities;
    return this;
  }

  public SetFiltersRequestDTO addEntitiesItem(ExternalEntityDTO entitiesItem) {
    if (this.entities == null) {
      this.entities = new ArrayList<>();
    }
    this.entities.add(entitiesItem);
    return this;
  }

   /**
   * A list of external entities
   * @return entities
  **/
  @ApiModelProperty(value = "A list of external entities")
  public List<ExternalEntityDTO> getEntities() {
    return entities;
  }

  public void setEntities(List<ExternalEntityDTO> entities) {
    this.entities = entities;
  }

  public SetFiltersRequestDTO bulkGroup(BulkGroupDTO bulkGroup) {
    this.bulkGroup = bulkGroup;
    return this;
  }

   /**
   * Get bulkGroup
   * @return bulkGroup
  **/
  @ApiModelProperty(value = "")
  public BulkGroupDTO getBulkGroup() {
    return bulkGroup;
  }

  public void setBulkGroup(BulkGroupDTO bulkGroup) {
    this.bulkGroup = bulkGroup;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SetFiltersRequestDTO setFiltersRequest = (SetFiltersRequestDTO) o;
    return Objects.equals(this.entities, setFiltersRequest.entities) &&
        Objects.equals(this.bulkGroup, setFiltersRequest.bulkGroup);
  }

  @Override
  public int hashCode() {
    return Objects.hash(entities, bulkGroup);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SetFiltersRequestDTO {\n");
    
    sb.append("    entities: ").append(toIndentedString(entities)).append("\n");
    sb.append("    bulkGroup: ").append(toIndentedString(bulkGroup)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

