/*
 * Integration Layer Configuration API
 * This is a REST API specification for Integration Layer Configuration application.
 *
 * OpenAPI spec version: TRUNK-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.amdocs.aia.il.configuration.client.dto;

import java.util.Objects;
import java.util.Arrays;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets SourceTargetType
 */
public enum SourceTargetTypeDTO {
  
  SOURCE("SOURCE"),
  
  TARGET("TARGET");

  private String value;

  SourceTargetTypeDTO(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static SourceTargetTypeDTO fromValue(String value) {
    for (SourceTargetTypeDTO b : SourceTargetTypeDTO.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    return null;
  }
}

