/*
 * Integration Layer Configuration API
 * This is a REST API specification for Integration Layer Configuration application.
 *
 * OpenAPI spec version: TRUNK-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.amdocs.aia.il.configuration.client.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Upload Discovery File Response
 */
@ApiModel(description = "Upload Discovery File Response")

public class UploadDiscoveryFileResponseDTO {
  @JsonProperty("fileId")
  private String fileId = null;

  public UploadDiscoveryFileResponseDTO fileId(String fileId) {
    this.fileId = fileId;
    return this;
  }

   /**
   * File Id
   * @return fileId
  **/
  @ApiModelProperty(value = "File Id")
  public String getFileId() {
    return fileId;
  }

  public void setFileId(String fileId) {
    this.fileId = fileId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UploadDiscoveryFileResponseDTO uploadDiscoveryFileResponse = (UploadDiscoveryFileResponseDTO) o;
    return Objects.equals(this.fileId, uploadDiscoveryFileResponse.fileId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fileId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UploadDiscoveryFileResponseDTO {\n");
    
    sb.append("    fileId: ").append(toIndentedString(fileId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

